### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by philippeluickx** [softmonkeyjapan/angular-color-chooser#1]
I just did a user testing session and the colors did not show up on Internet Explorer. The options where there and clickable, but everything was just white...

**Comment by softmonkeyjapan** [comment]
Hi,

Thanks for your feeback. So I've tried using the directive on IE and as you noticed, it does not work. I believe this is because I'm using `style` (https://github.com/softmonkeyjapan/angular-color-chooser/blob/master/src/color-chooser.js#L80) instead of `ng-style` to set the background color of each element.

Will make a push soon, today or tomorrow.

**Comment by softmonkeyjapan** [comment]
You should update your bower : 

```
"dependencies": {
  "angular-color-chooser": "~0.1.2"
}
```

and then run `bower install` to update.

**Comment by philippeluickx** [comment]
Kudos for a quick and complete solution! Thanks mate!
